### ISSUE TITLE
entering time with keyboard breaks everything

### ISSUE THREAD

**Issue by 01shadowalker01** [candidosales/material-time-picker#1]
When I try to change the current time with keyboard and type numbers, 
Everything changes to undefined!
Here is what I'm talking about:
At the beginning, everything is normal:
![Screenshot (28)](https://user-images.githubusercontent.com/52736525/61024368-9af15180-a3c2-11e9-89a3-ed7ff687e029.png)
After typing "number" with the keyboard:
![Screenshot (29)](https://user-images.githubusercontent.com/52736525/61024432-dee45680-a3c2-11e9-908e-4d1cdc82633e.png)
If it also does not allow user to enter string characters it would be much better!

**Comment by Sparker73** [comment]
I realize about it when clearing the input but it is just the same after editing and moving the focus away from the input. My workaround sets a predefined value when the change event brings no data. I guess that you can do the same but analyzing what the event brings up after a manual edit and deal with it. I have seen 8 different timePicker components but this is the only one that fits into the Material2 inputs but we have to deal with this bugs. I hope this can help or at least hold it up until a fix is released. Also, it could be wonderful if the control could be nulled by setting the input var `userTime` to null, it will be handy in some situations as well as add the `disabled` functionality.

```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  name = 'Angular';
  private exportTime = { hour: 7, minute: 15, meriden: 'PM', format: 12 };

  onChangeHour(event) {
    console.log('event', event);
    if ( event && event.format ) {
      this.exportTime = {
        hour: +event.hour,
        format: event.format,
        meriden: event.meriden,
        minute: +event.minute
      };
    } else {
      this.exportTime = {
        hour: 0,
        format: 12,
        meriden: 'AM',
        minute: 0
      };
    }
  }
}
```

**Comment by 01shadowalker01** [comment]
Thank you very much for time you spent explaining your problem👌

**Comment by candidosales** [comment]
It was added the `disabled` and `readonly` functions: https://github.com/candidosales/material-time-picker/pull/4/files

Thanks @rafaeldcastro! :)
