### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by dpaniq** [candidosales/material-time-picker#34]
Hello,
I have an error.
`@candidosales/material-time-picker@2.7.0: The engine "node" is incompatible with this module. Expected version ">=14.0.0 <17.0.0". Got "18.12.1"`
Is it possible to update your lib to 18+?

**Comment by passtech** [comment]
https://github.com/candidosales/material-time-picker/pull/40

**Comment by candidosales** [comment]
Thanks, @passtech, for the improvement! @dpaniq It's fixed! :)

I'll generate a new version.

**Comment by candidosales** [comment]
@dpaniq You can use the 2.8.0v. It's already been published. https://www.npmjs.com/package/@candidosales/material-time-picker?activeTab=versions
